package Acme::CPANLists::Import::PerlDancerAdvent::2010_12_17;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2010/17] (retrieved on 2016-11-24). Visit the URL for the full contents.",entries=>[{module=>"Catalyst::Authentication::Credential::Twitter"},{module=>"Dancer::Plugin::Auth::Twitter"},{module=>"Net::Twitter"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2010 (day 17)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2010 (day 17)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2010/17> (retrieved on 2016-11-24). Visit the URL for the full contents.

