package Acme::CPANLists::Import::PerlDancerAdvent::2010_12_19;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2010/19] (retrieved on 2016-11-24). Visit the URL for the full contents.",entries=>[{module=>"Apache::Session"},{module=>"Dancer"},{module=>"Dancer::Serializer::Abstract"},{module=>"Dancer::Serializer::UUEncode"},{module=>"Data::Dumper"},{module=>"JSON"},{module=>"Storable"},{module=>"XML::Simple"},{module=>"YAML"},{module=>"YAML::Tiny"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2010 (day 19)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2010 (day 19)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2010/19> (retrieved on 2016-11-24). Visit the URL for the full contents.

