package Acme::CPANLists::Import::PerlDancerAdvent::2010_12_23;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2010/23] (retrieved on 2016-11-24). Visit the URL for the full contents.",entries=>[{module=>"DBIx::Class::ResultSet"},{module=>"Dancer::Logger::PSGI"},{module=>"Dancer::Logger::Spinner"},{module=>"Dancer::Logger::Syslog"},{module=>"Dancer::Plugin::DBIC"},{module=>"Dancer::Plugin::Database"},{module=>"Dancer::Plugin::Mongo"},{module=>"Dancer::Plugin::Params::Normalization"},{module=>"Dancer::Plugin::REST"},{module=>"Dancer::Plugin::SiteMap"},{module=>"Dancer::Template::Mason"},{module=>"Dancer::Template::Semantic"},{module=>"Dancer::Template::Tenjin"},{module=>"Dancer::Template::Tiny"},{module=>"Dancer::Template::Xslate"},{module=>"HTML::Mason"},{module=>"Plack"},{module=>"Sys::Syslog"},{module=>"Template::Tiny"},{module=>"Tenjin"},{module=>"Text::MicroTemplate"},{module=>"Text::Xslate"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2010 (day 23)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2010 (day 23)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2010/23> (retrieved on 2016-11-24). Visit the URL for the full contents.

