package Acme::CPANLists::Import::PerlDancerAdvent::2010_12_09;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2010/9] (retrieved on 2016-11-24). Visit the URL for the full contents.",entries=>[{module=>"Dancer::Plugin::Ajax"},{module=>"Dancer::Template::Mason"},{module=>"Mason"},{module=>"Plack"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2010 (day 9)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2010 (day 9)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2010/9> (retrieved on 2016-11-24). Visit the URL for the full contents.

