package Acme::CPANLists::Import::PerlDancerAdvent::2010_12_20;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2010/20] (retrieved on 2016-11-24). Visit the URL for the full contents.",entries=>[{module=>"Dancer::Logger::Abstract"},{module=>"Dancer::Logger::Spinner"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2010 (day 20)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2010 (day 20)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2010/20> (retrieved on 2016-11-24). Visit the URL for the full contents.

