package Acme::CPANLists::Import::PerlDancerAdvent::2010_12_21;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2010/21] (retrieved on 2016-11-24). Visit the URL for the full contents.",entries=>[{module=>"Dancer::ModuleLoader"},{module=>"Dancer::Session::Abstract"},{module=>"Dancer::Session::Cookie"},{module=>"Dancer::Session::KiokuDB"},{module=>"Data::Visitor"},{module=>"KiokuDB"},{module=>"KiokuDB::TypeMap"},{module=>"Moose"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2010 (day 21)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2010 (day 21)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2010/21> (retrieved on 2016-11-24). Visit the URL for the full contents.

