package Acme::CPANLists::Import::PerlDancerAdvent::2010_12_15;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2010/15] (retrieved on 2016-11-24). Visit the URL for the full contents.",entries=>[{module=>"DBD::SQLite"},{module=>"DBI"},{module=>"File::Slurp"},{module=>"Math::Base36"},{module=>"Template"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2010 (day 15)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2010 (day 15)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2010/15> (retrieved on 2016-11-24). Visit the URL for the full contents.

