package Acme::CPANLists::Import::PerlDancerAdvent::2010_12_18;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2010/18] (retrieved on 2016-11-24). Visit the URL for the full contents.",entries=>[{module=>"DBI"},{module=>"Dancer"},{module=>"Dancer::App"},{module=>"Dancer::Handler"},{module=>"Dancer::Logger::Abstract"},{module=>"Dancer::Plugin::Database"},{module=>"Dancer::Request"},{module=>"Dancer::Route"},{module=>"Dancer::Serializer::Abstract"},{module=>"Dancer::Session::Abstract"},{module=>"Dancer::Template::Abstract"},{module=>"PSGI"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2010 (day 18)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2010 (day 18)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2010/18> (retrieved on 2016-11-24). Visit the URL for the full contents.

