package Acme::CPANLists::Import::PerlDancerAdvent::2010_12_07;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2010/7] (retrieved on 2016-11-24). Visit the URL for the full contents.",entries=>[{module=>"Catalyst::Plugin::CookiedSession"},{module=>"Crypt::CBC"},{module=>"Crypt::Rijndael"},{module=>"Dancer::Session"},{module=>"Dancer::Session::Cookie"},{module=>"Dancer::Session::Memcached"},{module=>"Plack::Middleware::Session::Cookie"},{module=>"String::CRC32"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2010 (day 7)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2010 (day 7)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2010/7> (retrieved on 2016-11-24). Visit the URL for the full contents.

