package Acme::CPANLists::Import::PerlDancerAdvent::2010_12_10;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2010/10] (retrieved on 2016-11-24). Visit the URL for the full contents.",entries=>[{module=>"Dancer"},{module=>"Plack"},{module=>"Plack::Middleware::ReverseProxy"},{module=>"Plack::Runner"},{module=>"Starman"},{module=>"Task::Dancer"},{module=>"Task::Plack"},{module=>"Template"},{module=>"Twiggy"},{module=>"Web::Hippie"},{module=>"local::lib"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2010 (day 10)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2010 (day 10)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2010/10> (retrieved on 2016-11-24). Visit the URL for the full contents.

