#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;
use FindBin '$Bin';

use App::CreateAcmeCPANListsImportModules;
use Perinci::Sub::Util qw(gen_curried_sub);
use Perinci::CmdLine::Any;

my @days = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 23);

gen_curried_sub(
    'App::CreateAcmeCPANListsImportModules::create_acme_cpanlists_import_modules',
    {
        modules => [
            {
                name => '2010',
                url => "http://advent.perldancer.org/2010/",
                extract_urls => [map {"http://advent.perldancer.org/2010/$_"} @days],
                summary => 'Modules mentioned in PerlDancer Advent Calendar 2010',
            },
            (map {
                +{
                    name => sprintf("2010_12_%02d", $_),
                    url => "http://advent.perldancer.org/2010/$_",
                    summary => "Modules mentioned in PerlDancer Advent Calendar 2010 (day $_)",
                } } @days),
        ],
        namespace => 'Acme::CPANLists::Import::PerlDancerAdvent',
        user_agent => 'Mozilla/5.0',
        dist_dir => "$Bin/..",
    },
    'app',
);

Perinci::CmdLine::Any->new(
    url => '/main/app',
    log => 1,
)->run;
